eProjectP3/eProjectP3/Controllers/HomeController.cs
using eProjectP3.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eProjectP3.Controllers
{
    public class HomeController : Controller
    {
        private eProjectP3Context db = new eProjectP3Context();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        [HttpPost]
        public ActionResult Search(string searchText)
        {
            var medicalResults = db.medical_application.Where(m => m.Name.Contains(searchText)).ToList();
            var scientificResults = db.scientific_application.Where(s => s.Name.Contains(searchText)).ToList();
            var combinedResults = new List<object>();
            combinedResults.AddRange(medicalResults);
            combinedResults.AddRange(scientificResults);
            ViewBag.SearchResults = combinedResults;
            return View("Index");
        }
    }
}

eProjectP3/eProjectP3/Controllers/medical_applicationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using eProjectP3.Data;
using eProjectP3.Models;

namespace eProjectP3.Controllers
{
    public class medical_applicationController : Controller
    {
        private eProjectP3Context db = new eProjectP3Context();

        // GET: medical_application
        /* public ActionResult Index()
         {
             ViewBag.Categories = new SelectList(db.medical_type, "Medicine_Type_Name", "Medicine_Type_Name");
             var medical_application = db.medical_application.Include(m => m.medical_type);
             return View(medical_application.ToList());
         }*/

        public ActionResult Index(string categoryFilter, string sortOrder, int? page)
        {
            var products = db.medical_application.Include(m => m.medical_type);

            // Apply filters
            if (!string.IsNullOrEmpty(categoryFilter) && categoryFilter != "All Categories")
            {
                products = products.Where(m => m.medical_type.Medicine_Type_Name == categoryFilter);
            }

            // Sorting
            switch (sortOrder)
            {
                case "Name (A-Z)":
                    products = products.OrderBy(m => m.Name);
                    break;
                case "Name (Z-A)":
                    products = products.OrderByDescending(m => m.Name);
                    break;
                case "Cost (Low to High)":
                    products = products.OrderBy(m => m.Cost);
                    break;
                case "Cost (High to Low)":
                    products = products.OrderByDescending(m => m.Cost);
                    break;
                default:

                    products = products.OrderBy(m => m.Name);
                    break;
            }
            int pageSize = 12;
            int pageNumber = (page ?? 1);
            var productsToShow = products.Skip((pageNumber - 1) * pageSize).Take(pageSize).ToList();
            ViewBag.CurrentPage = pageNumber;
            ViewBag.TotalPages = (int)Math.Ceiling((double)products.Count() / pageSize);
            ViewBag.Categories = new SelectList(db.medical_type, "Medicine_Type_Name", "Medicine_Type_Name");
            return View(productsToShow);
        }

        // GET: medical_application/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            medical_application medical_application = db.medical_application.Find(id);
            if (medical_application == null)
            {
                return HttpNotFound();
            }
            return View(medical_application);
        }

        // GET: medical_application/Create
        public ActionResult Create()
        {
            ViewBag.Medicine_Type_ID = new SelectList(db.medical_type, "Medicine_Type_ID", "Medicine_Type_Name");
            return View();
        }

        // POST: medical_application/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Medicine_ID,Medicine_Type_ID,Img,Cost,Code,Name")] medical_application medical_application)
        {
            if (ModelState.IsValid)
            {
                db.medical_application.Add(medical_application);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Medicine_Type_ID = new SelectList(db.medical_type, "Medicine_Type_ID", "Medicine_Type_Name", medical_application.Medicine_Type_ID);
            return View(medical_application);
        }

        // GET: medical_application/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            medical_application medical_application = db.medical_application.Find(id);
            if (medical_application == null)
            {
                return HttpNotFound();
            }
            ViewBag.Medicine_Type_ID = new SelectList(db.medical_type, "Medicine_Type_ID", "Medicine_Type_Name", medical_application.Medicine_Type_ID);
            return View(medical_application);
        }

        // POST: medical_application/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Medicine_ID,Medicine_Type_ID,Img,Cost,Code,Name")] medical_application medical_application)
        {
            if (ModelState.IsValid)
            {
                db.Entry(medical_application).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Medicine_Type_ID = new SelectList(db.medical_type, "Medicine_Type_ID", "Medicine_Type_Name", medical_application.Medicine_Type_ID);
            return View(medical_application);
        }

        // GET: medical_application/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            medical_application medical_application = db.medical_application.Find(id);
            if (medical_application == null)
            {
                return HttpNotFound();
            }
            return View(medical_application);
        }

        // POST: medical_application/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            medical_application medical_application = db.medical_application.Find(id);
            db.medical_application.Remove(medical_application);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

eProjectP3/eProjectP3/Controllers/scientific_applicationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using eProjectP3.Data;
using eProjectP3.Models;

namespace eProjectP3.Controllers
{
    public class scientific_applicationController : Controller
    {
        private eProjectP3Context db = new eProjectP3Context();

        // GET: scientific_application
        public ActionResult Index()
        {
            return View(db.scientific_application.ToList());
        }

        // GET: scientific_application/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            scientific_application scientific_application = db.scientific_application.Find(id);
            if (scientific_application == null)
            {
                return HttpNotFound();
            }
            return View(scientific_application);
        }

        // GET: scientific_application/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: scientific_application/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Apparatus_ID,Img,Cost,Description,Name")] scientific_application scientific_application)
        {
            if (ModelState.IsValid)
            {
                db.scientific_application.Add(scientific_application);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(scientific_application);
        }

        // GET: scientific_application/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            scientific_application scientific_application = db.scientific_application.Find(id);
            if (scientific_application == null)
            {
                return HttpNotFound();
            }
            return View(scientific_application);
        }

        // POST: scientific_application/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Apparatus_ID,Img,Cost,Description,Name")] scientific_application scientific_application)
        {
            if (ModelState.IsValid)
            {
                db.Entry(scientific_application).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(scientific_application);
        }

        // GET: scientific_application/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            scientific_application scientific_application = db.scientific_application.Find(id);
            if (scientific_application == null)
            {
                return HttpNotFound();
            }
            return View(scientific_application);
        }

        // POST: scientific_application/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            scientific_application scientific_application = db.scientific_application.Find(id);
            db.scientific_application.Remove(scientific_application);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

eProjectP3/eProjectP3/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About Us - Clinic Management</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
        }

        header {
            background-color: #333;
            color: white;
            text-align: center;
            padding: 1em 0;
        }

        section {
            max-width: 800px;
            margin: auto;
            padding: 20px;
            background-color: white;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            margin-top: 20px;
        }

        h1 {
            color: white;
        }

        p {
            line-height: 1.6em;
            color: #666;
        }
    </style>
</head>

<body>

    <header>
        <h1>About Us</h1>
    </header>

    <section>
        <h2>Welcome to Clinic Management</h2>
        <p>
            At Clinic Management, we strive to provide comprehensive solutions for healthcare professionals.
            Our services include the sale of pharmaceuticals, medical equipment, and the facilitation of medical education through specialized courses.
        </p>

        <h2>Our Mission</h2>
        <p>
            Our mission is to enhance healthcare delivery by offering top-notch products and educational programs.
            We aim to empower medical professionals with the knowledge and tools they need to provide exceptional patient care.
        </p>

        <h2>What We Offer</h2>
        <p>
            <ul>
                <li>Quality pharmaceuticals to meet diverse healthcare needs.</li>
                <li>State-of-the-art medical equipment for effective diagnosis and treatment.</li>
                <li>Specialized courses in the field of medicine to foster continuous learning.</li>
            </ul>
        </p>
    </section>

</body>

</html>

eProjectP3/eProjectP3/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contact Us</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f8f8f8;
            color: #333;
        }

        header {
            background-color: #333;
            color: white;
            text-align: center;
            padding: 1em 0;
        }

        main {
            max-width: 800px;
            margin: 20px auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0,0,0,0.1);
        }

        h2 {
            color: #333;
        }

        h3 {
            color: #555;
        }

        address {
            margin-top: 20px;
            font-style: normal;
            line-height: 1.6;
        }

        abbr {
            text-decoration: none;
            color: #333;
        }

        a {
            color: #007bff;
            text-decoration: none;
        }

            a:hover {
                text-decoration: underline;
            }

        #map {
            height: 300px;
            margin-top: 20px;
            border-radius: 8px;
            overflow: hidden;
        }
    </style>
</head>
<body>

    <header>
        <h1>Contact Us</h1>
    </header>

    <main>

        <address>
            <strong>Our Address:</strong><br>
            Can Tho, Viet Nam
        </address>

        <address>
            <strong>Contact Information:</strong><br>
            <abbr title="Phone">Phone:</abbr> 425.555.0100
        </address>

        <address>
            <strong>Email:</strong> <a href="mailto:Support@example.com">cusc.ctu.vn</a><br>
            <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br>
            <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
        </address>

        <div id="map">
            <a href="https://maps.app.goo.gl/C4N9kSQDFgZr7SKz6" target="_blank">
                <img src="~/Img/map.png" style="width:100%" alt="Map Image">
            </a>
        </div>
    </main>

    
</body>
</html>

eProjectP3/eProjectP3/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    var searchResults = ViewBag.SearchResults as List<object>;
}
@using eProjectP3.Models
<main>

    <section class="hero">
        <div class="hero-content">
            <h1 class="hero-title">Healthcare Management System</h1>
            <p class="lead">Empowering Healthcare Professionals and Businesses</p>
            <a href="#" class="btn btn-primary btn-md">Explore Features &raquo;</a>
        </div>
    </section>

    <section class="features">
        <div class="row">
            <div class="col-md-3 feature">
                <h2>Scientific Applications</h2>
                <p>Track medical equipment for healthcare and laboratory use.</p>
                <a href="#" class="btn btn-outline-dark">Learn more &raquo;</a>
            </div>
            <div class="col-md-3 feature">
                <h2>Medical Applications</h2>
                <p>Manage inventory and pharmaceuticals for medical facilities.</p>
                <a href="#" class="btn btn-outline-dark">Learn more &raquo;</a>
            </div>
            <div class="col-md-3 feature">
                <h2>Education Applications</h2>
                <p>Organize workshops, training, and professional development.</p>
                <a href="#" class="btn btn-outline-dark">Learn more &raquo;</a>
            </div>
            <div class="col-md-3 feature">
                <h2>Business Applications</h2>
                <p>Handle sales and revenue tracking for healthcare businesses.</p>
                <a href="#" class="btn btn-outline-dark">Learn more &raquo;</a>
            </div>
        </div>
    </section>
    <div class="col-md feature justify-content-center">
        <h2>Search Products</h2>
        @using (Html.BeginForm("Search", "Home", FormMethod.Post, new { @class = "text-center" }))
        {
            <div class="input-group d-flex justify-content-center">
                <input type="text" name="searchText" class="form-control" placeholder="Enter product name" />
                <button type="submit" class="btn btn-primary">Search</button>
            </div>
        }
    </div>
    <section class="search-results">
        @if (ViewBag.SearchResults != null && ViewBag.SearchResults.Count > 0)
        {
            <h2>Search Results</h2>
            foreach (var result in ViewBag.SearchResults)
            {
                <div class="product row">
                    @if (result is medical_application)
                    {
                        var medicalProduct = result as medical_application;
                        <div class="col-md-3">
                            <img src="~/Img/@medicalProduct.Img" alt="Medical Product Image" class="img-fluid" />
                        </div>
                        <div class="col-md-6">
                            <h3>Medical Product: @medicalProduct.Name</h3>
                            <p>Medicine Type: @medicalProduct.medical_type.Medicine_Type_Name</p>
                            <p>Cost: @medicalProduct.Cost</p>
                        </div>
                        <div class="col-md-3 text-right">
                            <a href="@Url.Action("Details", "medical_application", new { id = medicalProduct.Medicine_ID })" class="btn btn-primary">Detail</a>
                        </div>
                    }
                    else if (result is scientific_application)
                    {
                        var scientificProduct = result as scientific_application;
                        <div class="col-md-3">
                            <img src="~/Img/@scientificProduct.Img" alt="Scientific Product Image" class="img-fluid" />
                        </div>
                        <div class="col-md-6">
                            <h3>Scientific Product: @scientificProduct.Name</h3>
                            <p>Description: @scientificProduct.Description</p>
                            <p>Cost: @scientificProduct.Cost</p>
                        </div>
                        <div class="col-md-3 text-right">
                            <a href="@Url.Action("Details", "scientific_application", new { id = scientificProduct.Apparatus_ID })" class="btn btn-primary">Detail</a>
                        </div>
                    }
                </div>
            }
        }

    </section>
</main>

<style>
    main {
        padding: 20px;
    }

    .hero {
        background-image: url('/Img/Clinic Management System.png');
        background-size: cover;
        color: black;
        text-align: center;
        padding: 100px 0;
        font-weight: bold;
        text-shadow: 2px 2px 3px rgba(255, 255, 255, 1);
    }

    .hero-content {
        max-width: 600px;
        margin: 0 auto;
    }

    .hero-title {
        font-size: 3em;
        margin-bottom: 20px;
    }

    .lead {
        font-size: 2em;
        margin-bottom: 30px;
    }

    .btn {
        padding: 10px 20px;
        font-size: 1.2em;
        text-decoration: none;
        color: #fff;
    }

    .btn-primary {
        background-color: #007bff;
    }

    .btn-outline-dark {
        color: black;
        background-color: transparent;
        border: 2px solid #343a40;
    }

    .features {
        margin-top: 40px;
    }

    .feature {
        text-align: center;
        margin-bottom: 40px;
    }

        .feature h2 {
            font-size: 2em;
            margin-bottom: 20px;
        }

    .appointment {
        text-align: center;
        margin-top: 40px;
        margin-bottom: 40px;
    }
</style>